<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/monitoring" class="list-group-item">
          <h4 class="list-group-item-heading">Fiscalização</h4>
            <p class="list-group-item-text">Acesso aos módulos de fiscalização</p>
        </a>
        <a href="/used-fleet" class="list-group-item"><i class="fa fa-bus"></i> Frota Empenhada</a>
        <a href="/used-fleet" class="list-group-item"><i class="fa fa-check-square-o"></i> Viagens Realizadas</a>
        <a href="/used-fleet" class="list-group-item"><i class="fa fa-sitemap"></i> Cumprimento Itinerário</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Fiscalização</li>
      </ol> 
      <div class="jumbotron">
        <h1>Fiscalização</h1>
        <p class="lead">O módulo <b>Fiscalização</b> dá suporte à fiscalização.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/fiscal.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>