<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da frota</p>
        </a>
        <?$authNamespace = new Zend_Session_Namespace('userInformation');
          $institution = $authNamespace->institution;
          if($institution != 1){?>
        <a href="/fleet/new" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> Novo</a>
        <?}?>
        <a href="/fleet/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="#" class="list-group-item active"><i class="fa fa-file"></i> Segunda via</a>
        <?if($institution == 1){?>
        <a href="/fleet/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
        <a href="/fleet/review" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Cadastros realizados</a>
          <?}?>
          <?if($this->institution == 3){?>
        <a href="/fleet/process" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Veículos em processo</a>
          <?}?>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Frota</a></li>
        <li class="active">Segunda via</li>
      </ol>
      <div class="page-header">
        <h1>Segunda via <small>peça a segunda via do seu CRV</small></h1>
        <hr>
        <form class="form-horizontal" action="/fleet/ask-crv" method="post">
      		<div class="form-group">
           	<label for="reason" class="col-lg-2 control-label optional">Motivo</label>
	          <div class="col-lg-5">
	            <select name="reason" id="consortiumTransfer" class="form-control">
	                <option value="0">-- Selecione a motivo --</option>
	                <option value="1">Perda</option>
	                <option value="2">Roubo</option>
	                <option value="3">Inutilização</option>
	            </select>
	          </div>
          </div>
      		<div class="form-group">
            <label for="subject" class="col-lg-2 control-label optional">Justificativa</label>
            <div class="col-lg-5">
             <textarea name="body" class="form-control" rows="5" placeholder="escreva aqui o que aconteceu com seu CRV"></textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-5">
              <input type="submit" name="submit" id="submit" value="Pedir 2 via" class="col-lg-offset-5 btn btn-primary"> 
              <input type="hidden" name="vehicle_id" value="<?=$this->vehicleId?>">
            </div>
          </div>
        </form>
      </div>
    </div>
 	</div>
</div>