<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da frota</p>
        </a>
        <a href="/fleet/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <?$authNamespace = new Zend_Session_Namespace('userInformation');
          $institution = $authNamespace->institution;
          if($institution == 1){?>
        <a href="/fleet/report" class="list-group-item active"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
        <a href="/fleet/review-add" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Pedidos de cadastro <?if($this->vehiclesReviewedAdd){?><span class="badge"><?=$this->vehiclesReviewedAdd?></span><?}?></a>
        <a href="/fleet/review" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Cadastros realizados <?if($this->vehiclesReviewed){?><span class="badge"><?=$this->vehiclesReviewed?></span><?}?></a>
        <a href="/fleet/review-crv" class="list-group-item"><i class="fa fa-file"></i> Segunda via CRV <?if($this->vehiclesAskedCrv){?><span class="badge"><?=$this->vehiclesAskedCrv?></span><?}?></a>
        <a href="/fleet/review-down" class="list-group-item"><i class="fa fa-trash"></i> Pedidos de baixa <?if($this->vehiclesDown){?><span class="badge"><?=$this->vehiclesDown?></span><?}?></a>
        <?}?>
          <?if($this->institution == 3){?>
        <a href="/fleet/process" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Veículos em processo</a>
          <?}?>
          <?if($this->institution == 4){?>
            <a href="/fleet/report" class="list-group-item active"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
          <?}?>
      </div>
    </div>
    <div class="span9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Frota</a></li>
        <li class="active">Relatórios</li>
      </ol>
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Relação de Veículos Ativos</h2>
          <p>Lista completa dos veículos ativos do sistema.</p>
          <p><a href="/fleet/report-active" class="btn btn-default">emitir relatório</a></p>
        </div>
        <div class="span6 well">
          <h2>Relação de Todos Veículos</h2>
          <p>Lista completa dos veículos do sistema.</p>
          <p><a href="/fleet/report-all" class="btn btn-default">emitir relatório</a></p>
        </div>

      </div>
    </div>
    <div class="span9">
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Resumo de Veículos Ativos <p>  </p></h2>         
        
          <p>Total de chassis ativos:               
          <?if(count($this->list)){?>
            <?foreach($this->list as $vehicle){?>
                <tr><td><strong><?=$vehicle->chassi_count?> ativos. </strong></tb </td></tr>                 
                </p><p> Idade média dos chassis ativos : 
                <tr><td><strong><?=$vehicle->chassi_life_cycle?> anos. </strong></tb </td></tr> 
                </p><p> Idade média das carrocerias ativas :
                <tr><td><strong><?=$vehicle->chassi_life_cycle?> anos. </strong></tb </td></tr> 
                <?}
            }?>
            
          
         
          </div>
      </div>
    </div>
  </div>
</div>
