<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/used-fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota Empenhada</h4>
            <p class="list-group-item-text">Acesso aos dados dos veículos utilizados</p>
        </a>
        <a href="/used-fleet/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/used-fleet/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/monitoring">Fiscalização</a></li>
        <li class="active">Frota Empenhada</li>
      </ol> 
      <div class="jumbotron">
        <h1>Frota Empenhada</h1>
        <p class="lead">A Frota Empenhada são todos os veículos que efetivamente fizeram viagens no sistema.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/usedfleet.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>
