<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="list-group">
        <a href="/used-fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota Empenhada</h4>
            <p class="list-group-item-text">Acesso aos dados dos veículos utilizados</p>
        </a> 
        <a href="/used-fleet/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/used-fleet/report" class="list-group-item active"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="span9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/monitoring">Fiscalização</a></li>
        <li><a href="/used-fleet">Frota Empenhada</a></li>
        <li class="active">Relatório</li>
      </ol>
    <h2 align="center">Veículos Empenhados no Sistema</h2>
    <table class="col-sm-12">
    	<tr>
    		<td>
			    <h2 align="center"><small>Período de Empenho</small></h2>
			    <h4 align="center"><?=$this->date[0]?> às <?=$this->date[1]?></h4>
		    </td>
    		<td>
			    <h2 align="center"><small>Hora Pico</small></h2>
			    <h4 align="center">
			    	Manhã <?=$this->hour[0][0]?> às <?=$this->hour[0][1]?>
			        - Tarde <?=$this->hour[1][0]?> às <?=$this->hour[1][1]?>
			    </h4> 
   			 </td>	
   		 </tr>
	</table>

	<div class="row">
		<div class="col-sm-6"><br><br>
			<table class="table table-bordered table-hover" border="1">
				<thead>
					<tr>
						<th>Data</th>
						<th>Pico Manhã</th>
						<th>Pico Tarde</th>						
						<th>Pico</th>
					</tr>
				</thead>
				<tbody>
				<tr>
					<? 
					foreach ($this->data as $body){?>
                     <tr>
						<?foreach ($body as $value) {?>						
							<td><?=$value?></td>						
						<?}?>
					 </tr>
					<?}?>	
				</tr>
				</tbody>
			</table>
		</div>
		<div class="col-sm-6"><br><br>
			<table class="table table-bordered table-hover" border="1">
				<thead>
            		<th rowspan="2"><center>Referência</center></th>
            		<th colspan="3"><center>Média</center></th>          		
					<tr>
						<th><center>Dia Útil</center></th>
						<th><center>Sábado</center></th>
						<th><center>Domingo</center></th>
					</tr>
				</thead>
				<tbody>
					<tr>
					<? 
					foreach ($this->average as $body){?>
                     <tr>
						<?foreach ($body as $value) {?>						
							<td><center><?=$value?></center></td>						
						<?}?>
					 </tr>
					<?}?>	
				</tr>
				</tbody>
			</table>
		</div>		
	</div>
</div>