<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/used-fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota Empenhada</h4>
            <p class="list-group-item-text">Acesso aos dados dos veículos utilizados</p>
        </a>    
        <a href="/used-fleet/view" class="list-group-item active"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/used-fleet/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9"> 
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/monitoring">Fiscalização</a></li>
        <li><a href="/used-fleet">Frota Empenhada</a></li>
        <li class="active">Pesquisa</li>
      </ol>
      <div class="page-header">
        <h1>Pesquisa <small>pesquise aqui os veículos empenhados</small></h1>
        <hr>
          <form class="form-inline" action="/used-fleet/view" method="post" role="form">
            <div class="form-group col-md-5">
              <input type="text" class="form-control" placeholder="número da linha" name="field" value="<?=$this->field?>">
            </div>
            <button type="submit" class="btn btn-primary">Pesquisar</button>
          </form>
          <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Data</th>
            <th>Linha</th>
            <th>Veículo</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->line)){

              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->start_date?></a></td>
                  <td><?=$body->line?></a></td>
                  <td><?=$body->vehicle_number?></td>
                </tr>
            <?} } 
                 else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhuma linha na pesquisa.</td>
              </tr>
            <?}
            ?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->line)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml', array('field' => $this->field)); }?>
      </div>
    </div><!--/span-->
  </div>
</div>